### PR TITLE
Add csv.simulate example in R

### PR DESCRIPTION
**Pull request by garland-culbreth**
The example creates input files for the same simulation as simulate_xam.py but stops before running the simulate commands, for users who might want to use R to create input files before running the simulation with the python commands.

### CODE REVIEW

**Comment by bradbell** [comment]
This example breaks one of my documentation rules. To be specific, all of the examples must run as automated tests. This ensures that as the package changes, all the examples still work.  

The script 
https://github.com/bradbell/at_cascade/blob/master/bin/check_all.sh
runs all the at-cascade automated tests.

**Comment by bradbell** [comment]
Are you planning to change this example, and check_all.sh so that it is an automated that that runs in the context of this project. If not, please close this pull request.

**Comment by garland-culbreth** [comment]
Eventually, but I'll open a new PR once it's updated to comply with this.

**Comment by bradbell** [comment]
You can use this pull request and re-open it.

**Pull request closed without merging**
