### PR TITLE
prior_pred: Initial module and rough stability test

### PR DESCRIPTION
**Pull request by garland-culbreth**
@bradbell @ntemiq @garland-culbreth 

In this we've made the module for copying a node's dismod.db and emptying its data table to then run fit and sample to predict from the priors alone.

The next steps we've planned are:
1. Get `at_cascade/csv/predict_prior.py` to produce the output fit_predict.csv and sam_predict.csv files storing the prior predictions.
2. Build out the initial stability test in `example/csv/prior_pred.py` into a full test
3. Add a flag to `at_cascade/csv/predict.py` and its downstream modules to tell them whether we want prior predictions; default False to leave regular functionality unaffected
4. Add conditionals where needed in that module tree to invoke `at_cascade/csv/predict_prior.py` when flagged

Much of `example/csv/prior_pred.py` is still duplicated from `example/csv/break_fit_pred.py`, this is because right now it's being used as a very rough stability test (ie, does the script run without failing); once we get to (2) that step will involve changing the rest of that file to align with what we're actually using it for as well.

### CODE REVIEW

**Comment by bradbell** [comment]
In the at_cascade.git directory, please try running
```
bin/check_all.sh
```

**Comment by garland-culbreth** [comment]
Adding the output of the bin/check_all.sh command in this text file: [log.txt](https://github.com/user-attachments/files/15930836/log.txt)

**Comment by bradbell** [comment]
> Adding the output of the bin/check_all.sh command in this text file: [log.txt](https://github.com/user-attachments/files/15930836/log.txt)

The key here is the last line of log.txt:
```
check_all.sh: OK
```
If that does not appear, then something went wrong.

**Comment by bradbell** [comment]
I tried to run bin/check_all.sh and got the output below. I suspect that ``xrst`` is not in your execution path so testing ``bin/run_xrst.sh`` was skipped on your system:
```
at_cascade.git>bin/check_all.sh
bin/check_copy.sh
bin/check_copy.sh: OK
bin/check_invisible.sh
check_invisible.sh: OK
bin/check_tab.sh
check_tab.sh: OK
bin/check_version.sh
check_version.sh OK
bin/run_xrst.sh
xrst --local_toc --target html --html_theme sphinx_rtd_theme --index_page_name at_cascade 
xrst: Error
The file at_cascade/csv/predict_prior.py
used in a toc_table command does not contain any begin commands.
project_directory = /home/bradbell/repo/at_cascade.git
page = csv.module
file = at_cascade/csv/__init__.py
line = 123
```

**Comment by bradbell** [comment]
```
at_cascade.git>bin/check_all.sh
bin/check_copy.sh
bin/check_copy.sh: OK
bin/check_invisible.sh
check_invisible.sh: OK
bin/check_tab.sh
check_tab.sh: OK
bin/check_version.sh
check_version.sh OK
bin/run_xrst.sh
xrst --local_toc --target html --html_theme sphinx_rtd_theme --index_page_name at_cascade 

warning: group_name = default
The following files have pages with the empty group name
but they are not in any xrst_toc commands starting at the root_file for the default group
   example/csv/prior_pred.py
Using following input_files: git ls-files
sphinx-build -b html -j 1 build/rst build/html
rm -r build/html/_sources
cp -r build/rst/_sources build/html/_sources
xrst: See warnings above
run_xrst.sh: aboring due to xrst errors above
at_cascade.git>
```

**Comment by garland-culbreth** [comment]
I've been running into issues with the scripts in `/bin`, specifically `check_invisible.sh` and `check_version.sh`, due to syntactic differences with OSX. This [discussion](https://stackoverflow.com/questions/26081375/bsd-sed-extra-characters-at-the-end-of-d-command) covers the issue I encountered

**Comment by garland-culbreth** [comment]
Closing this PR and opening a new one with the same changes but cleaner files

**Pull request closed without merging**
