### PR TITLE
Add FAQ and Sarah's wishlist to new documentation build.

### PR DESCRIPTION
**Pull request by garland-culbreth**
Testing pull request from fork.

### CODE REVIEW

**Comment by bradbell** [comment]
I just make a local copy of the pull request:
```
at_cascade.git>git branch
  master
* pull_1
```
And in the pull_1 branch I executed
```
at_cascade.git>bin/check_xrst.sh
xrst --local_toc --target html --html_theme sphinx_rtd_theme --index_page_name at_cascade 
xrst: Error
The file wishlist_swh_gc.xrst does not exist
It was used by a toc_table command
project_directory = /home/bradbell/repo/at_cascade.git
page = at_cascade
file = at_cascade.xrst
line = 51

check_xrst.sh: aboring due to xrst errors above
```
1. In at_cascade.xrst you should remove the line
    wishlist_swh_gc.xrst

2. You should merge the current master to you branch. For example, check_xrst.sh has changed to run_xrst.sh.

3. I have been keeping to the convention that the source code files should fit in 80 columns; i.e., I use newlines
   to break up long line. The newlines are chosen to make the source test more readable. Please try and do this with
   the file faq.xrst

**Comment by garland-culbreth** [comment]
New commits should address these!
1. check_xrst.sh flagged that line because the file had been missing.
2. This has been done.
3. This has also been done. There is one hyperlink on line 39 in faq.xrst which is longer than 80 characters, and I'm not sure how to break links across lines in XRST, so I have that one on a long line by itself.

**Comment by bradbell** [comment]
1. I use sphinx_rtd_theme for in run_xrst.sh because it is just for testing 
   (and I like to see how the doc will look if I change themes).
   The file that is used to build the online documentation is:
   https://github.com/bradbell/at_cascade/blob/master/.readthedocs.yaml

2. No Random Effects: Allow for empty child_rate.csv table if we don’t want to include any RE’s in a fit.
    I have tested this an an emtpy child_rate.csv file works for me. 
    I think this is just a question of what and empty file looks like; i.e. for me it is a file with only the header line.
    I have added to following under csv_fit@Input Files@child_rate.csv@rate_name  (perhaps this will make it clearer) :
    "If a rate does does not appear, it will have no random effects."
    
3.  It seems that the automatic adjustment of line lengths changes the max_filt wish list entry,
     but there are no real changes. Is this correct ?

**Comment by garland-culbreth** [comment]
Just pushed two more changed to address these!

1. Reverted back to sphinx_rtd_theme.
2. Sounds perfect! Removed that item from the list.
3. That's correct. I adjusted the line lengths but didn't change the actual content at all.

**Pull request closed without merging**
