### PR TITLE
Add remark to csv_simulate documentation about meas_mean corresponding to truth

### PR DESCRIPTION
**Pull request by garland-culbreth**

### CODE REVIEW

**Comment by garland-culbreth** [comment]
We thought adding this extra line to this description would be useful for users, to make it extra clear that the meas_mean is also equivalent to the truth used for the sim.

**Comment by bradbell** [comment]
The problem here is that 'true value' has not been defined. Does the following for you and Sarah ?

This corresponds to the simulation value for all the model variables and covariates.
This can be thought of as the true value for the average of the integrand that is measured.

**Comment by garland-culbreth** [comment]
That works perfectly! Updated the text in the most recent commit.

**Comment by bradbell** [comment]
If you look at
https://github.com/bradbell/at_cascade/commits/master

You will notice that all my log entries start with the branch that the edits are done on.  E.g. my changes to pull request #3 start with ``pull_3:`` . It would help if your log entries started with a_short_name_that_you_choose: ; e.g. in this case it could have been ``meas_mean:`` .

**Pull request merged**
